"""将已保存的全局稀疏地图 HDF5 转成 Foxglove 可直接读取的 PLY 点云。"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np


def _normalize_log_odds(log_odds: np.ndarray, low: float, high: float) -> np.ndarray:
    if log_odds.size == 0:
        return np.empty((0,), dtype=np.float32)
    span = max(float(high - low), 1e-6)
    return np.clip((log_odds.astype(np.float64) - float(low)) / span, 0.0, 1.0).astype(np.float32)


def _to_points_neu(indices_ned: np.ndarray, resolution: float) -> np.ndarray:
    if indices_ned.size == 0:
        return np.empty((0, 3), dtype=np.float64)
    points_ned = (indices_ned.astype(np.float64) + 0.5) * float(resolution)
    points_neu = points_ned.copy()
    points_neu[:, 2] *= -1.0
    return points_neu


def _point_colors_from_log_odds(log_odds: np.ndarray, occupied_threshold: float | None = None) -> np.ndarray:
    if log_odds.size == 0:
        return np.empty((0, 3), dtype=np.float64)
    if occupied_threshold is None:
        occupied_threshold = float(np.median(log_odds))
    active = log_odds >= float(occupied_threshold)
    colors = np.zeros((log_odds.size, 3), dtype=np.float64)
    if np.any(active):
        colors[active] = np.asarray([0.9, 0.2, 0.2], dtype=np.float64)
    if np.any(~active):
        free_ratio = _normalize_log_odds(log_odds[~active], np.min(log_odds[~active]), np.max(log_odds[~active])) if np.ptp(log_odds[~active]) > 0 else np.zeros_like(log_odds[~active], dtype=np.float32)
        colors[~active] = np.column_stack((
            0.2 + 0.6 * free_ratio,
            0.3 + 0.5 * free_ratio,
            0.9,
        ))
    return colors


def convert_global_map_hdf5_to_foxglove_ply(
    input_h5: str | Path,
    output_ply: str | Path,
    *,
    occupied_threshold: float | None = None,
    max_points: int | None = None,
) -> Path:
    """Convert the saved global sparse map HDF5 into a standard PLY point cloud.

    The map file generated by GlobalSparseOccupancyMap.save() stores voxel indices and
    log-odds in a NED coordinate system. This converter transforms them to NEU, which is
    compatible with the conventional OpenGL/3D-view workflow used by Foxglove, and
    exports a binary PLY with x/y/z and RGB fields.
    """
    input_path = Path(input_h5)
    output_path = Path(output_ply)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    import h5py

    with h5py.File(input_path, "r") as h5_file:
        if "voxel_indices_ned" not in h5_file:
            raise ValueError(f"{input_path} does not contain 'voxel_indices_ned'.")
        if "log_odds" not in h5_file:
            raise ValueError(f"{input_path} does not contain 'log_odds'.")

        indices = np.asarray(h5_file["voxel_indices_ned"], dtype=np.int64)
        log_odds = np.asarray(h5_file["log_odds"], dtype=np.float32)
        resolution = float(h5_file.attrs.get("resolution", 0.3))
        threshold = float(h5_file.attrs.get("occupied_threshold", 0.7)) if occupied_threshold is None else float(occupied_threshold)

    if indices.size == 0 or log_odds.size == 0:
        raise ValueError(f"{input_path} contains no point cloud data.")
    if indices.shape[0] != log_odds.shape[0]:
        raise ValueError(
            f"voxel_indices_ned length ({indices.shape[0]}) does not match log_odds length ({log_odds.shape[0]})."
        )

    points_neu = _to_points_neu(indices, resolution)
    colors = _point_colors_from_log_odds(log_odds, threshold)

    if max_points is not None and points_neu.shape[0] > int(max_points):
        keep = np.linspace(0, points_neu.shape[0] - 1, num=int(max_points), dtype=int)
        points_neu = points_neu[keep]
        colors = colors[keep]

    vertices = np.empty(
        points_neu.shape[0],
        dtype=np.dtype(
            [
                ("x", "<f4"),
                ("y", "<f4"),
                ("z", "<f4"),
                ("red", "u1"),
                ("green", "u1"),
                ("blue", "u1"),
            ]
        ),
    )
    vertices["x"] = points_neu[:, 0]
    vertices["y"] = points_neu[:, 1]
    vertices["z"] = points_neu[:, 2]
    vertices["red"] = np.clip(colors[:, 0] * 255.0, 0, 255).astype(np.uint8)
    vertices["green"] = np.clip(colors[:, 1] * 255.0, 0, 255).astype(np.uint8)
    vertices["blue"] = np.clip(colors[:, 2] * 255.0, 0, 255).astype(np.uint8)

    header = (
        "ply\n"
        "format binary_little_endian 1.0\n"
        "comment Converted from global sparse occupancy map for Foxglove\n"
        "comment Coordinates: x=North, y=East, z=Up (NED Down negated)\n"
        f"element vertex {vertices.shape[0]}\n"
        "property float x\n"
        "property float y\n"
        "property float z\n"
        "property uchar red\n"
        "property uchar green\n"
        "property uchar blue\n"
        "end_header\n"
    ).encode("ascii")

    with output_path.open("wb") as ply_file:
        ply_file.write(header)
        vertices.tofile(ply_file)

    return output_path


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Convert saved global sparse map HDF5 into a Foxglove-readable PLY point cloud."
    )
    parser.add_argument("input_h5", type=str, help="Path to the saved map HDF5 file.")
    parser.add_argument("output_ply", type=str, help="Path for the generated PLY file.")
    parser.add_argument(
        "--occupied-threshold",
        type=float,
        default=None,
        help="Override the occupied log-odds threshold for coloring.",
    )
    parser.add_argument(
        "--max-points",
        type=int,
        default=None,
        help="Optional limit on output point count.",
    )
    return parser


def main() -> None:
    parser = _build_parser()
    args = parser.parse_args()
    path = convert_global_map_hdf5_to_foxglove_ply(
        args.input_h5,
        args.output_ply,
        occupied_threshold=args.occupied_threshold,
        max_points=args.max_points,
    )
    print(f"Foxglove PLY exported to: {path}")


if __name__ == "__main__":
    main()
